const MASTER_FACULTY_ROSTER = [
    {
        "s_no": 1,
        "school": "SBS",
        "department": "Biochemistry",
        "name": "Mr. A. Benno Susai Vijayakumar",
        "designation": "Assistant Professor",
        "email": "bennosusaivijayakumar_bi2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 2,
        "school": "SBS",
        "department": "Biochemistry",
        "name": "Mr. T. Antony Diwakar Chandran",
        "designation": "Assistant Professor",
        "email": "antonydiwakarchandran_bi2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 3,
        "school": "SBS",
        "department": "Biochemistry",
        "name": "Dr. P. G. Geegi",
        "designation": "Assistant Professor",
        "email": "geegi_bi2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 4,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. V. Swabna",
        "designation": "Assistant Professor",
        "email": "swabna_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 5,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. A. Edward",
        "designation": "Assistant Professor",
        "email": "edward_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 6,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. A. Asha Monica",
        "designation": "Assistant Professor",
        "email": "ashamonica_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 7,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. J. Arutchelvi",
        "designation": "Assistant Professor",
        "email": "arutchelvij_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 8,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. C. Muthusamy",
        "designation": "Assistant Professor",
        "email": "muthusamy_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 9,
        "school": "SBS",
        "department": "Biotechnology",
        "name": "Dr. R. Tamilvanan",
        "designation": "Assistant Professor",
        "email": "tamilvanan_bt2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 10,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. S. Sahaya Sathish",
        "designation": "Associate Professor",
        "email": "sahayasathish_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 11,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. S. R. Senthilkumar",
        "designation": "Associate Professor",
        "email": "senthilkumar_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 12,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. A. Egbert Selwin Rose",
        "designation": "Associate Professor",
        "email": "egbertselwinrose_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 13,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. S. Soosairaj",
        "designation": "Associate Professor",
        "email": "soosairaj_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 14,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. T. Francis Xavier",
        "designation": "Associate Professor",
        "email": "francisxavier_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 15,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. M. Francis Sathiyaseelan",
        "designation": "Associate Professor",
        "email": "francissathiyaseelan_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 16,
        "school": "SBS",
        "department": "Botany",
        "name": "Rev. Dr. L. John Peter Arulanandam, SJ",
        "designation": "Assistant Professor",
        "email": "johnpeterarulanandam_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 17,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. H. David Raja",
        "designation": "Associate Professor",
        "email": "davidraja_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 18,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. A. Johny Kumar Tagore",
        "designation": "Assistant Professor",
        "email": "jktagore_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 19,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. S. Anusuya",
        "designation": "Assistant Professor",
        "email": "anusuya_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 20,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. M. Bastin Churchill",
        "designation": "Assistant Professor",
        "email": "bastinchurchill_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 21,
        "school": "SBS",
        "department": "Botany",
        "name": "Dr. G. Chelladurai",
        "designation": "Assistant Professor",
        "email": "chelladurai_bo1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 22,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. G. John",
        "designation": "Associate Professor",
        "email": "john_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 23,
        "school": "SCO",
        "department": "Commerce",
        "name": "Mr. D. Maria Antony",
        "designation": "Assistant Professor",
        "email": "mariaantony_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 24,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. V. Bastin Jerome",
        "designation": "Associate Professor",
        "email": "bastinjerome_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 25,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. M. Antony Jesuraja",
        "designation": "Assistant Professor",
        "email": "antonyjesuraja_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 26,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. A. Francis Vijayakumar",
        "designation": "Assistant Professor",
        "email": "francisvijayakumar_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 27,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. M. Julias Ceasar",
        "designation": "Associate Professor",
        "email": "juliasceasar_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 28,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. Arockia Rajasekar",
        "designation": "Assistant Professor",
        "email": "arockiarajasekar_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 29,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. S. Aruldass",
        "designation": "Assistant Professor",
        "email": "aruldass_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 30,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. A. Sahayaraj Alexander",
        "designation": "Assistant Professor",
        "email": "sahayarajalexander_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 31,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. L. Georgia",
        "designation": "Assistant Professor",
        "email": "georgia_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 32,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. Dennis Edward Fernando",
        "designation": "Assistant Professor",
        "email": "dennisedwardfernando_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 33,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. J. Vinoth Kumar",
        "designation": "Assistant Professor",
        "email": "vinothkumar_co1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 34,
        "school": "SCO",
        "department": "Commerce",
        "name": "Mr. S. Kirubakaran",
        "designation": "Assistant Professor",
        "email": "kirubakaran_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 35,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. B. Augustine Arockiaraj",
        "designation": "Assistant Professor",
        "email": "augustinearockiaraj_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 36,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. S. Jerome",
        "designation": "Assistant Professor",
        "email": "jerome_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 37,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. B. Nalini",
        "designation": "Assistant Professor",
        "email": "nalini_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 38,
        "school": "SCO",
        "department": "Commerce",
        "name": "Ms. C. Soundarya",
        "designation": "Assistant Professor",
        "email": "soundarya_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 39,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. A. Ignatius",
        "designation": "Assistant Professor",
        "email": "ignatiusa_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 40,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. J. Berkmans",
        "designation": "Assistant Professor",
        "email": "berkmansj_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 41,
        "school": "SCO",
        "department": "Commerce",
        "name": "Dr. A. Mariya Selvi",
        "designation": "Assistant Professor",
        "email": "mariyaselvia_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 42,
        "school": "SCO",
        "department": "Commerce",
        "name": "Mr. V. Perumal",
        "designation": "Assistant Professor",
        "email": "perumal_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 43,
        "school": "SCO",
        "department": "Commerce Business Analytics",
        "name": "Ms. H. Bella Josepha",
        "designation": "Assistant Professor",
        "email": "bellajosepha_cb2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 44,
        "school": "SCO",
        "department": "Commerce Business Analytics",
        "name": "Mr. S. Santhosh",
        "designation": "Assistant Professor",
        "email": "santhosh_cb2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 45,
        "school": "SCO",
        "department": "Commerce Business Analytics",
        "name": "Dr. P. Navomi Nithila",
        "designation": "Assistant Professor",
        "email": "navominithila_cb2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 46,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. F. X. Virgin Fraga",
        "designation": "Assistant Professor",
        "email": "virginfraga_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 47,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. D. John Prabakaran",
        "designation": "Assistant Professor",
        "email": "johnprabakaran_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 48,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. J. Rajees",
        "designation": "Assistant Professor",
        "email": "rajees_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 49,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. N. Maheswari",
        "designation": "Assistant Professor",
        "email": "maheswari_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 50,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. J. Arputha Sahaya Raj",
        "designation": "Assistant Professor",
        "email": "arputhasahayaraj_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 51,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. B. Fathimamary",
        "designation": "Assistant Professor",
        "email": "fathimamary_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 52,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. R. Arul",
        "designation": "Assistant Professor",
        "email": "arul_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 53,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. S. Arumugam",
        "designation": "Assistant Professor",
        "email": "arumugam_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 54,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. H. Lakshmipriya",
        "designation": "Assistant Professor",
        "email": "lakshmipriya_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 55,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Dr. A. Sarlin Venotha",
        "designation": "Assistant Professor",
        "email": "sarlinvenotha_co2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 56,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Ms. N. Sumithra",
        "designation": "Assistant Professor",
        "email": "sumithra_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 57,
        "school": "SCO",
        "department": "Commerce CA",
        "name": "Mr. J. Renish",
        "designation": "Assistant Professor",
        "email": "renish_cc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 58,
        "school": "SCO",
        "department": "Commerce Honours",
        "name": "Mr. G. Prabhakaran",
        "designation": "Assistant Professor",
        "email": "prabakaran_cr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 59,
        "school": "SCO",
        "department": "Commerce Honours",
        "name": "Dr. I. Jerry Richards",
        "designation": "Professor of Practice",
        "email": "jerryrichards_cr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 60,
        "school": "SCO",
        "department": "Commerce Strategic Finance",
        "name": "Ms. A. Mary Magdalene",
        "designation": "Assistant Professor",
        "email": "marymagdalene_cr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 61,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Mr. A. Charles",
        "designation": "Assistant Professor",
        "email": "charles_ai2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 62,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Dr. J. Hirudhaya Mary Asha",
        "designation": "Assistant Professor",
        "email": "hirudhayaasha_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 63,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Dr. S. Josephine Theresa",
        "designation": "Assistant Professor",
        "email": "josephinetheresa_ai2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 64,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Dr. T. Thilagavathi",
        "designation": "Assistant Professor",
        "email": "thilagavathi_ai2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 65,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Mr. M. Jesudoss",
        "designation": "Assistant Professor",
        "email": "jesudoss_ai2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 66,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Dr. S. Lakshmanan",
        "designation": "Assistant Professor",
        "email": "lakshmanan_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 67,
        "school": "SCS",
        "department": "Artificial Intelligence",
        "name": "Mr. C. Mohanraja",
        "designation": "Assistant Professor",
        "email": "mohanraja_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 68,
        "school": "SCS",
        "department": "B.Voc SD & SA",
        "name": "Ms. B. Geno Cinthia",
        "designation": "Assistant Professor",
        "email": "genocinthia_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 69,
        "school": "SCS",
        "department": "B.Voc SD & SA",
        "name": "Dr. V. A. Jane",
        "designation": "Assistant Professor",
        "email": "janeva_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 70,
        "school": "SCS",
        "department": "B.Voc SD & SA",
        "name": "Dr. S. Banumathi",
        "designation": "Assistant Professor",
        "email": "banumathi_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 71,
        "school": "SCS",
        "department": "B.Voc SD & SA",
        "name": "Ms. S. Merlin Sofia",
        "designation": "Assistant Professor",
        "email": "merlinsofia_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 72,
        "school": "SCS",
        "department": "B.Voc SD & SA",
        "name": "Ms. J .Francis Julee Rajam",
        "designation": "Assistant Professor",
        "email": "francisjuleerajam_ss1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 73,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. S. Britto Ramesh Kumar",
        "designation": "Associate Professor",
        "email": "brittorameshkumar_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 74,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. A. Aloysius",
        "designation": "Assistant Professor",
        "email": "aloysius_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 75,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. V. Jude Nirmal",
        "designation": "Assistant Professor",
        "email": "judenirmal_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 76,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Rev. Dr. S. Arul Oli, SJ",
        "designation": "Assistant Professor",
        "email": "aruloli_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 77,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Rev. Dr. S. Santiago, SJ",
        "designation": "Assistant Professor",
        "email": "santiago_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 78,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. A. Vimal Jerald",
        "designation": "Assistant Professor",
        "email": "vimaljerald_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 79,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. George Gabriel Richard Roy",
        "designation": "Assistant Professor",
        "email": "georgegabrielrichardroy_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 80,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. A. Angelpreethi",
        "designation": "Assistant Professor",
        "email": "angelpreethi_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 81,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. G. Arockia Sahaya Sheela",
        "designation": "Assistant Professor",
        "email": "arockiasahayasheela_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 82,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. P. Joseph Charles",
        "designation": "Assistant Professor",
        "email": "josephcharles_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 83,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. A. Jenifer Jothi Mary",
        "designation": "Assistant Professor",
        "email": "jeniferjothimary_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 84,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. K. Maheswaran",
        "designation": "Assistant Professor",
        "email": "maheswaran_cs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 85,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. J. Antony John Prabu",
        "designation": "Assistant Professor",
        "email": "antonyjohnprabu_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 86,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. S. Thulasi Bharathi",
        "designation": "Assistant Professor",
        "email": "thulasibharathi_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 87,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. S. Sathyapriya",
        "designation": "Assistant Professor",
        "email": "sathyapriya_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 88,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Ms. M. Merla Agnes Mary",
        "designation": "Assistant Professor",
        "email": "merlaagnesmary_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 89,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. K. Subash",
        "designation": "Assistant Professor",
        "email": "subash_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 90,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Ms. Sherine Dominick",
        "designation": "Assistant Professor",
        "email": "sherinedominick_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 91,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. M. Venkatesh Saravanakumar",
        "designation": "Assistant Professor",
        "email": "venkateshsaravanakumarm_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 92,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Ms. P. Lekka",
        "designation": "Assistant Professor",
        "email": "lekka_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 93,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Ms. I. Reshma Monica",
        "designation": "Assistant Professor",
        "email": "reshmamonica_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 94,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Ms. A. H. Amalorpava Akila",
        "designation": "Assistant Professor",
        "email": "amalorpvaakila_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 95,
        "school": "SCS",
        "department": "Computer Science",
        "name": "Dr. R. Sakthi Raman",
        "designation": "Assistant Professor",
        "email": "sakthiraman_cs2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 96,
        "school": "SCS",
        "department": "Data Science",
        "name": "Dr. T. Rajaretnam",
        "designation": "Head of the Department",
        "email": "rajaretnam_ds2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 97,
        "school": "SCS",
        "department": "Data Science",
        "name": "Dr. V. Arul Kumar",
        "designation": "Assistant Professor",
        "email": "arulkumar_ds2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 98,
        "school": "SCS",
        "department": "Data Science",
        "name": "Dr. M. Kriushanth",
        "designation": "Assistant Professor",
        "email": "kriushanth_ds2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 99,
        "school": "SCS",
        "department": "Data Science",
        "name": "Dr. A. Beatrice Dorothy",
        "designation": "Assistant Professor",
        "email": "beatricedorothy_ds2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 100,
        "school": "SCS",
        "department": "Data Science",
        "name": "Dr. K. Loura Jency",
        "designation": "Assistant Professor",
        "email": "lourajency_ ds2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 101,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. A. Antony Prakash",
        "designation": "Assistant Professor",
        "email": "antonyprakash_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 102,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. K. R. Martin",
        "designation": "Assistant Professor",
        "email": "martin_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 103,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. V. Maria Antoniate Martin",
        "designation": "Assistant Professor",
        "email": "mariaantoniatemartin_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 104,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. P. Bastin Thiyagaraj",
        "designation": "Assistant Professor",
        "email": "bastinthiyagaraj_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 105,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. C. Venish Raja",
        "designation": "Assistant Professor",
        "email": "venishraja_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 106,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. R. Mangai Begum",
        "designation": "Assistant Professor",
        "email": "mangaibegum_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 107,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. D. Richard",
        "designation": "Assistant Professor",
        "email": "richard_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 108,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. I. Carol",
        "designation": "Assistant Professor",
        "email": "carol_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 109,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. T. Nikil Prakash",
        "designation": "Assistant Professor",
        "email": "nikilprakasht_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 110,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. S. Hemalatha",
        "designation": "Assistant Professor",
        "email": "hemalatha_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 111,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Ms. D. Irine Auxilia Mary",
        "designation": "Assistant Professor",
        "email": "dirineauxiliamary_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 112,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Dr. J. Jenifer",
        "designation": "Assistant Professor",
        "email": "jeniferj_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 113,
        "school": "SCS",
        "department": "Information Technology",
        "name": "Ms. P. Sophiya",
        "designation": "Assistant Professor",
        "email": "sophiya_it2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 114,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. M. Thiagarajan",
        "designation": "Associate Professor",
        "email": "thiagarajan_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 115,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. Y. Dominic",
        "designation": "Associate Professor",
        "email": "dominic_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 116,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Umamaheswari",
        "designation": "Associate Professor",
        "email": "umamaheswari_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 117,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. A. Anthony Eldred",
        "designation": "Associate Professor",
        "email": "anthonyeldred_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 118,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. A. Praveen",
        "designation": "Associate Professor",
        "email": "praveen_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 119,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Christy Roja",
        "designation": "Assistant Professor",
        "email": "christyroja_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 120,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Maria Joseph",
        "designation": "Assistant Professor",
        "email": "mariajoseph_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 121,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Arockia Jeyakumar",
        "designation": "Assistant Professor",
        "email": "arockiajeyakumar_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 122,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. S. Ithaya Ezhil Manna",
        "designation": "Assistant Professor",
        "email": "ithayaezhilmanna_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 123,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. V. Vairaperumal",
        "designation": "Assistant Professor",
        "email": "vairaperumal_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 124,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. Geetha Sivaraman",
        "designation": "Assistant Professor",
        "email": "geethasivaraman_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 125,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Amalorpava Jerline",
        "designation": "Assistant Professor",
        "email": "amalorpavajerline_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 126,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. R. Lenin",
        "designation": "Assistant Professor",
        "email": "lenin_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 127,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Mr. S. Arul Gnanapragasam",
        "designation": "Assistant Professor",
        "email": "arulgnanapragasam_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 128,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. S. Aseervatham",
        "designation": "Assistant Professor",
        "email": "aseervatham_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 129,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Carmel Pushpa Raj",
        "designation": "Assistant Professor",
        "email": "carmel_ma1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 130,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. P. Lawrence Rozario Raj",
        "designation": "Assistant Professor",
        "email": "lawrencerozarioraj_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 131,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. J. Mercy Arokia Rani",
        "designation": "Assistant Professor",
        "email": "mercyarokiarani_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 132,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. A. Delman",
        "designation": "Assistant Professor",
        "email": "delman_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 133,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. S. Jai Roselin",
        "designation": "Assistant Professor",
        "email": "jairoselin_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 134,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. L. Saral",
        "designation": "Assistant Professor",
        "email": "saral_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 135,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. S. Sahaya Jernith",
        "designation": "Assistant Professor",
        "email": "sahayajernith_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 136,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. A. Arul Xavier",
        "designation": "Assistant Professor",
        "email": "arulxavier_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 137,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. E. Veronisha",
        "designation": "Assistant Professor",
        "email": "veronisha_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 138,
        "school": "SCS",
        "department": "Mathematics",
        "name": "Dr. P. Vishnu Kumar",
        "designation": "Assistant Professor",
        "email": "vishnukumar_ma2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 139,
        "school": "SCS",
        "department": "Statistics",
        "name": "Dr. R. Vijayakumar",
        "designation": "Assistant Professor",
        "email": "vijayakumar_st1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 140,
        "school": "SCS",
        "department": "Statistics",
        "name": "Dr. J. Glorypersial",
        "designation": "Assistant Professor",
        "email": "glorypersial_st1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 141,
        "school": "SCS",
        "department": "Statistics",
        "name": "Dr. T. Venkatesan",
        "designation": "Assistant Professor",
        "email": "venkatesan_st1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 142,
        "school": "SCS",
        "department": "Statistics",
        "name": "Dr. A. Philip Arokiadoss",
        "designation": "Assistant Professor",
        "email": "philiparokiadoss_st1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 143,
        "school": "SLC",
        "department": "English",
        "name": "Dr. V. Francis",
        "designation": "Associate Professor",
        "email": "francis_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 144,
        "school": "SLC",
        "department": "English",
        "name": "Dr. V. L. Jayapaul",
        "designation": "Associate Professor",
        "email": "jayapaul_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 145,
        "school": "SLC",
        "department": "English",
        "name": "Dr. J. John Love Joy",
        "designation": "Associate Professor",
        "email": "johnlovejoy_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 146,
        "school": "SLC",
        "department": "English",
        "name": "Dr. R. Qurshid Begum",
        "designation": "Associate Professor",
        "email": "qurshidbegum_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 147,
        "school": "SLC",
        "department": "English",
        "name": "Dr. M. John Britto",
        "designation": "Associate Professor",
        "email": "johnbritto_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 148,
        "school": "SLC",
        "department": "English",
        "name": "Rev. Dr. S. Paul Pragash, SJ",
        "designation": "Associate Professor",
        "email": "paulpragash_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 149,
        "school": "SLC",
        "department": "English",
        "name": "Dr. D. R. Edwin Christy",
        "designation": "Associate Professor",
        "email": "edwinchristy_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 150,
        "school": "SLC",
        "department": "English",
        "name": "Dr. R. Jayakanth",
        "designation": "Associate Professor",
        "email": "jayakanth_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 151,
        "school": "SLC",
        "department": "English",
        "name": "Dr. Cheryl Davis",
        "designation": "Assistant Professor",
        "email": "cheryldavis_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 152,
        "school": "SLC",
        "department": "English",
        "name": "Dr. M. Amutha",
        "designation": "Associate Professor",
        "email": "amutha_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 153,
        "school": "SLC",
        "department": "English",
        "name": "Mr. A. Abraham",
        "designation": "Assistant Professor",
        "email": "abraham_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 154,
        "school": "SLC",
        "department": "English",
        "name": "Dr. S. Jerald Sagaya Nathan",
        "designation": "Assistant Professor",
        "email": "jeraldsagayanathan_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 155,
        "school": "SLC",
        "department": "English",
        "name": "Dr. B. Sam Jerome Sharone",
        "designation": "Assistant Professor",
        "email": "samjeromesharone_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 156,
        "school": "SLC",
        "department": "English",
        "name": "Dr. J. Amalaveenus",
        "designation": "Assistant Professor",
        "email": "amalaveenus_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 157,
        "school": "SLC",
        "department": "English",
        "name": "Dr. S. Sajeev",
        "designation": "Assistant Professor",
        "email": "sajeev_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 158,
        "school": "SLC",
        "department": "English",
        "name": "Dr. M. S. Xavier Pradheep Singh",
        "designation": "Assistant Professor",
        "email": "xavierpradheepsingh_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 159,
        "school": "SLC",
        "department": "English",
        "name": "Ms. G. Annie Rose",
        "designation": "Assistant Professor",
        "email": "annierose_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 160,
        "school": "SLC",
        "department": "English",
        "name": "Mr. A. Nepolian",
        "designation": "Assistant Professor",
        "email": "nepolian_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 161,
        "school": "SLC",
        "department": "English",
        "name": "Mr. S. Ignatius Richard",
        "designation": "Assistant Professor",
        "email": "ignatiusrichards_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 162,
        "school": "SLC",
        "department": "English",
        "name": "Dr. Twin Antony Edward",
        "designation": "Assistant Professor",
        "email": "t.a.edward_en1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 163,
        "school": "SLC",
        "department": "English",
        "name": "Dr. A. Johnson Francis",
        "designation": "Assistant Professor",
        "email": "johnsonfrancis_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 164,
        "school": "SLC",
        "department": "English",
        "name": "Dr. D. Loyola Innaci",
        "designation": "Assistant Professor",
        "email": "loyolainnaci_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 165,
        "school": "SLC",
        "department": "English",
        "name": "Dr. J. Charles Arockiasamy",
        "designation": "Assistant Professor",
        "email": "ezhugnayiru_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 166,
        "school": "SLC",
        "department": "English",
        "name": "Dr. A. Ezhugnayiru",
        "designation": "Assistant Professor",
        "email": "charlesarockiasamy_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 167,
        "school": "SLC",
        "department": "English",
        "name": "Mr. I. Christhuraj",
        "designation": "Assistant Professor",
        "email": "christhuraj_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 168,
        "school": "SLC",
        "department": "English",
        "name": "Mr. S. Thiyagarajan",
        "designation": "Assistant Professor",
        "email": "thiyagarajan_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 169,
        "school": "SLC",
        "department": "English",
        "name": "Mr. A. Ukkirapandiyan",
        "designation": "Assistant Professor",
        "email": "ukkirapandian_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 170,
        "school": "SLC",
        "department": "English",
        "name": "Dr. D. Prasanth Arokia Samy",
        "designation": "Assistant Professor",
        "email": "prasantharokiasamy_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 171,
        "school": "SLC",
        "department": "English",
        "name": "Dr. A. Sangeeth Kumar",
        "designation": "Assistant Professor",
        "email": "sangeethkumar_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 172,
        "school": "SLC",
        "department": "English",
        "name": "Dr. J. Gilbert Mary",
        "designation": "Assistant Professor",
        "email": "gilbertmary_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 173,
        "school": "SLC",
        "department": "English",
        "name": "Ms. L. Virgin Francy",
        "designation": "Assistant Professor",
        "email": "virginfrancyl_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 174,
        "school": "SLC",
        "department": "English",
        "name": "Dr. P. Catherine Benita",
        "designation": "Assistant Professor",
        "email": "catherinebenita_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 175,
        "school": "SLC",
        "department": "English",
        "name": "Ms. M. Joyce Vinitha",
        "designation": "Assistant Professor",
        "email": "joycevinitha_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 176,
        "school": "SLC",
        "department": "English",
        "name": "Ms. R. Rekkani",
        "designation": "Assistant Professor",
        "email": "rekkani_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 177,
        "school": "SLC",
        "department": "English",
        "name": "Dr. H. Daniel Raj",
        "designation": "Assistant Professor",
        "email": "danielraj_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 178,
        "school": "SLC",
        "department": "English",
        "name": "Mr. S. Alfred Pravin",
        "designation": "Assistant Professor",
        "email": "alfredpravin_en2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 179,
        "school": "SLC",
        "department": "English",
        "name": "Mr. M. Manoj Kumar",
        "designation": "Assistant Professor",
        "email": "mmanojkumar_en1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 180,
        "school": "SLC",
        "department": "French",
        "name": "Ms. M. Mohanalakshmi",
        "designation": "Assistant Professor",
        "email": "mohanalakshmi_fr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 181,
        "school": "SLC",
        "department": "Hindi",
        "name": "Dr. S. Sreedevi",
        "designation": "Assistant Professor",
        "email": "sreedevi_hi1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 182,
        "school": "SLC",
        "department": "History",
        "name": "Rev. Dr. M. Arockiasamy Xavier SJ",
        "designation": "Associate Professor",
        "email": "arockiasamyxavier_hs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 183,
        "school": "SLC",
        "department": "History",
        "name": "Dr. S. Manikandan",
        "designation": "Assistant Professor",
        "email": "manikandan_hs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 184,
        "school": "SLC",
        "department": "History",
        "name": "Dr. J. Santhosh Kumar",
        "designation": "Assistant Professor",
        "email": "santhoshkumar_hs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 185,
        "school": "SLC",
        "department": "History",
        "name": "Dr. K. Lingammal",
        "designation": "Assistant Professor",
        "email": "lingammal_hs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 186,
        "school": "SLC",
        "department": "History",
        "name": "Dr. M. Britto Stalin",
        "designation": "Assistant Professor",
        "email": "brittostalin_hs1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 187,
        "school": "SLC",
        "department": "History",
        "name": "Mr.A.Amarnath",
        "designation": "Assistant Professor",
        "email": "amarnath_hs1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 188,
        "school": "SLC",
        "department": "History",
        "name": "Ms. T. Beatinal Amalorpava Mary",
        "designation": "Assistant Professor",
        "email": "beatinalaalorpavamary_hs1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 189,
        "school": "SLC",
        "department": "Sanskrit",
        "name": "Dr. M. S. Madhavachari",
        "designation": "Assistant Professor",
        "email": "madhavachari_sa1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 190,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. A. Joseph Sahayaraj",
        "designation": "Associate Professor",
        "email": "josephsahayaraj_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 191,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. G. Beschi",
        "designation": "Associate Professor",
        "email": "beschi_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 192,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. D. Wilson",
        "designation": "Associate Professor",
        "email": "wilson_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 193,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. J. Benjamin Aron Titus",
        "designation": "Assistant Professor",
        "email": "benjaminarontitus_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 194,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. A. Rajathi",
        "designation": "Assistant Professor",
        "email": "rajathi_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 195,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. S. Shagilabanu",
        "designation": "Assistant Professor",
        "email": "shagilabanu_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 196,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. A. Maria Dhanabal",
        "designation": "Assistant Professor",
        "email": "mariadhanabal_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 197,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. R. Nallamuthu",
        "designation": "Assistant Professor",
        "email": "nallamuthu_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 198,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. K. Anthony Raja",
        "designation": "Assistant Professor",
        "email": "anthonyraja_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 199,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. A. Adaikkalaraj",
        "designation": "Assistant Professor",
        "email": "adaikkalaraj_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 200,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. J. Saleth",
        "designation": "Assistant Professor",
        "email": "saleth_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 201,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. S. Arockia Dhanaraj",
        "designation": "Assistant Professor",
        "email": "arockiadhanaraj_ta1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 202,
        "school": "SLC",
        "department": "Tamil",
        "name": "Ms. S. Backya Selva Rathi",
        "designation": "Assistant Professor",
        "email": "backyaselvarathi_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 203,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. S. Srinivasan",
        "designation": "Assistant Professor",
        "email": "srinivasan_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 204,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. R. Murali Krishnan",
        "designation": "Assistant Professor",
        "email": "muralikrishnan_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 205,
        "school": "SLC",
        "department": "Tamil",
        "name": "Mr.I. Yogaraj",
        "designation": "Assistant Professor",
        "email": "yogaraj_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 206,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. L. Charles",
        "designation": "Assistant Professor",
        "email": "charles_ta1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 207,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. B. Johnson",
        "designation": "Assistant Professor",
        "email": "johnson_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 208,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. J. Stella Mary",
        "designation": "Assistant Professor",
        "email": "stellamary_ ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 209,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. M. Dhanalakshmi",
        "designation": "Assistant Professor",
        "email": "dhanalakshmi_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 210,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. L.Ruba",
        "designation": "Assistant Professor",
        "email": "ruba_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 211,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr.K.John Kennedy",
        "designation": "Assistant Professor",
        "email": "johnkennedy_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 212,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. I. Anto Monica",
        "designation": "Assistant Professor",
        "email": "antomonica_ta1@mail.sjctni.edu",
        "shift": "I",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 213,
        "school": "SLC",
        "department": "Tamil",
        "name": "Dr. L.  Arun Prakash",
        "designation": "Assistant Professor",
        "email": "arunprakashl_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 214,
        "school": "SLC",
        "department": "Tamil",
        "name": "Mr. B. Ezhilselvan",
        "designation": "Assistant Professor",
        "email": "ezhilselvan_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 215,
        "school": "SLC",
        "department": "Tamil",
        "name": "Ms. A. G.Umamaheswari",
        "designation": "Assistant Professor",
        "email": "umamaheswari_ta2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 216,
        "school": "SLC",
        "department": "Tamil",
        "name": "Mr.M.Raja",
        "designation": "Assistant Professor",
        "email": "raja_ta1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 217,
        "school": "SMS",
        "department": "BBA",
        "name": "MR. S. ARPUTHA RAJ",
        "designation": "ASSISTANT PROFESSOR",
        "email": "arputharaj_bu2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 218,
        "school": "SMS",
        "department": "BBA",
        "name": "MS. C.F. OCTOVIA ANTONY SESSAMMAL",
        "designation": "ASSISTANT PROFESSOR",
        "email": "octoviaantonysessammal_bu2@mail.sjc tni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 219,
        "school": "SMS",
        "department": "BBA",
        "name": "MR. D. RINALDO DE DAVID",
        "designation": "ASSISTANT PROFESSOR",
        "email": "rinaldodedavid_bu2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 220,
        "school": "SMS",
        "department": "BBA",
        "name": "MR. J. INIGO PAPU VINODHAN",
        "designation": "ASSISTANT PROFESSOR",
        "email": "inigopopuvinodhan_bu2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 221,
        "school": "SMS",
        "department": "BBA",
        "name": "Mr. B. Ananda Raj",
        "designation": "Assistant Professor",
        "email": "anandaraj_bu2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 222,
        "school": "SMS",
        "department": "BBA",
        "name": "Mr.K.Radhakrishnan",
        "designation": "Assistant Professor",
        "email": "radhakrishnan_bu2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 223,
        "school": "SMS",
        "department": "Counselling Psy",
        "name": "Dr. A. John Balaiah",
        "designation": "Assistant Professor",
        "email": "johnbalaiah_cp2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 224,
        "school": "SMS",
        "department": "Counselling Psy",
        "name": "Dr. V. Suganthi",
        "designation": "Assistant Professor",
        "email": "suganthiv_cp2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 225,
        "school": "SMS",
        "department": "Counselling Psy",
        "name": "Ms. F. M. Christeeba",
        "designation": "Assistant Professor",
        "email": "christeeba_cp2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 226,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. M. Suvakkin",
        "designation": "Associate Professor",
        "email": "suvakkin_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 227,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. G. Iruthayaraj",
        "designation": "Associate Professor",
        "email": "iruthayaraj_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 228,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. A. Justin Thiraviam",
        "designation": "Associate Professor",
        "email": "justinthiraviam_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 229,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. K. A. Michael",
        "designation": "Associate Professor",
        "email": "michael_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 230,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. S. P. Robert",
        "designation": "Associate Professor",
        "email": "robert_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 231,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. J. Vasantha Arockiaselvi",
        "designation": "Assistant Professor",
        "email": "vasanthaarockiaselvi_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 232,
        "school": "SMS",
        "department": "Economics",
        "name": "Ms. P. Prarthna",
        "designation": "Assistant Professor",
        "email": "prarthna_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 233,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. R. Ganesasubramanian",
        "designation": "Assistant Professor",
        "email": "ganesasubramanian_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 234,
        "school": "SMS",
        "department": "Economics",
        "name": "Dr. P. Jayakumar",
        "designation": "Assistant Professor",
        "email": "jayakumar_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 235,
        "school": "SMS",
        "department": "Economics",
        "name": "Ms. J. Jayashree Naiken",
        "designation": "Assistant Professor",
        "email": "jayashreenaiken_ec1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 236,
        "school": "SMS",
        "department": "HRM",
        "name": "Rev. Dr. K. Arockiam, SJ",
        "designation": "Associate Professor",
        "email": "arockiamk_hr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 237,
        "school": "SMS",
        "department": "HRM",
        "name": "Mr. G. Louis Victor",
        "designation": "Assistant Professor",
        "email": "louisvictor_hr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 238,
        "school": "SMS",
        "department": "HRM",
        "name": "Dr. J. Michael Raj",
        "designation": "Assistant Professor",
        "email": "michaelraj_hr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 239,
        "school": "SMS",
        "department": "HRM",
        "name": "Dr. J. Wilfred Angello Gerald",
        "designation": "Assistant Professor",
        "email": "wilfredangellogerald_hr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 240,
        "school": "SMS",
        "department": "HRM",
        "name": "Dr. Y. Vijila",
        "designation": "Assistant Professor",
        "email": "vijila_hr1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 241,
        "school": "SMS",
        "department": "HRM",
        "name": "Dr. J. Vincent Xavier",
        "designation": "Assistant Professor",
        "email": "vincentxavier_hr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 242,
        "school": "SMS",
        "department": "HRM",
        "name": "Ms. C. Annie Jane",
        "designation": "Assistant Professor",
        "email": "anniejane_hr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 243,
        "school": "SMS",
        "department": "HRM",
        "name": "Dr. V.  Udhaya Geetha",
        "designation": "Assistant Professor",
        "email": "udhayageetha_hr2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 244,
        "school": "SMS",
        "department": "Physical Education",
        "name": "Dr. A. Prem Edwin",
        "designation": "Physical Director",
        "email": "premedwin_sp1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 245,
        "school": "SMS",
        "department": "Physical Education",
        "name": "Mr. S. Sriram",
        "designation": "Assistant Professor",
        "email": "sriram_pe1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 246,
        "school": "SMS",
        "department": "Physical Education",
        "name": "Dr. P. Ramesh",
        "designation": "Assistant Professor",
        "email": "ramesh_pe1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 247,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Dr. S.Tamilarasi",
        "designation": "Assistant Professor",
        "email": "tamilarasi_vt1@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 248,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Ms. K. Ramya",
        "designation": "Assistant Professor",
        "email": "ramya_vc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 249,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Dr. E. V. Prabha",
        "designation": "Assistant Professor",
        "email": "prabhaev_vc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 250,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Ms.N.Srimohanapriya",
        "designation": "Assistant Professor",
        "email": "srimohanapriya_vt1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 251,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Mr. G. Sathish",
        "designation": "Assistant Professor",
        "email": "sathish_vt1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 252,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Mr. C .Naveen Kumar",
        "designation": "Assistant Professor",
        "email": "naveenkumar_vt1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 253,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Mr. X. Maria Bastin",
        "designation": "Assistant Professor",
        "email": "mariabastin_vt1@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 254,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Mr. C. Jawahar",
        "designation": "Assistant Professor",
        "email": "jawahar_vc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 255,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Ms.T.Deepa",
        "designation": "Assistant Professor",
        "email": "deepa_vc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 256,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Rev. Dr. Xavier Antony, SJ",
        "designation": "Assistant Professor",
        "email": "",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 257,
        "school": "SMS",
        "department": "Visual Communication",
        "name": "Mr. A. Kingsly",
        "designation": "Assistant Professor",
        "email": "kingsly_vc2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 258,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Rose Venis",
        "designation": "Associate Professor",
        "email": "rosevenis_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 259,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Irudaya Jothi",
        "designation": "Associate Professor",
        "email": "irudayajothi_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 260,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. S. Antony Sakthi",
        "designation": "Associate Professor",
        "email": "antonysakthi_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 261,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Edwin Vasu",
        "designation": "Associate Professor",
        "email": "edwinvasu_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 262,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. S. Stella Shalini",
        "designation": "Associate Professor",
        "email": "stellashalini_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 263,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Simi",
        "designation": "Associate Professor",
        "email": "simi_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 264,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. S. Britto",
        "designation": "Associate Professor",
        "email": "britto_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 265,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Ceril Jeoffrey",
        "designation": "Assistant Professor",
        "email": "ceriljeoffrey_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 266,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. C. Rajarathinam",
        "designation": "Assistant Professor",
        "email": "rajarathinam_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 267,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. S. Mangalaraj",
        "designation": "Assistant Professor",
        "email": "mangalaraj_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 268,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Leostandly",
        "designation": "Assistant Professor",
        "email": "leostandly_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 269,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Arun Viveke",
        "designation": "Assistant Professor",
        "email": "arunviveke_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 270,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. I. Arockiaraj",
        "designation": "Assistant Professor",
        "email": "arockiaraj_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 271,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Rev. Dr. A. Sebastin Thangadurai, SJ",
        "designation": "Assistant Professor",
        "email": "sebastinthangadurai_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 272,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Rev. Fr. A.I. Rajasekaran SJ",
        "designation": "Assistant Professor",
        "email": "rajasekaran_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 273,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. A. Arun Joseph Rosario",
        "designation": "Assistant Professor",
        "email": "arunjosephrosario_ch1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 274,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. P. Arockia Doss",
        "designation": "Assistant Professor",
        "email": "arockiadoss_ch2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 275,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. JK. Alphonsa Juliet Helina",
        "designation": "Assistant Professor",
        "email": "alphonsajuliethelina_ch2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 276,
        "school": "SPS",
        "department": "Chemistry",
        "name": "Dr. S. Celestina",
        "designation": "Assistant Professor",
        "email": "drcelestina_ch2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 277,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. P. Subbuthai",
        "designation": "Assistant Professor",
        "email": "subbuthai_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 278,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. V. Manickam",
        "designation": "Assistant Professor",
        "email": "manickam_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 279,
        "school": "SPS",
        "department": "Electronics",
        "name": "Rev. Fr. J. John Wilson, SJ",
        "designation": "Assistant Professor",
        "email": "johnwilson_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 280,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. A. Arputharaj",
        "designation": "Assistant Professor",
        "email": "arputharaj_ el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 281,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. S. Mary  Margaret",
        "designation": "Assistant Professor",
        "email": "marymargarets_ el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 282,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. K. Priya Dharshini",
        "designation": "Assistant Professor",
        "email": "priyadharshini_ el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 283,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. M. Sappani Muthu",
        "designation": "Assistant Professor",
        "email": "sappanimuthu_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 284,
        "school": "SPS",
        "department": "Electronics",
        "name": "Dr. K. Karuppasamy",
        "designation": "Assistant Professor",
        "email": "karuppasamy_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 285,
        "school": "SPS",
        "department": "Electronics",
        "name": "Mr. V. Victor Remy",
        "designation": "Assistant Professor",
        "email": "victorremy_el2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 286,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. I. Johnson",
        "designation": "Associate Professor",
        "email": "johnson_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 287,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. B. Kanickairaj",
        "designation": "Associate Professor",
        "email": "kanickairaj_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 288,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. J. Charles",
        "designation": "Associate Professor",
        "email": "charles_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 289,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. P. Christuraj",
        "designation": "Associate Professor",
        "email": "christuraj_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 290,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. A. Maggie Dayana",
        "designation": "Associate Professor",
        "email": "maggiedayana_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "F"
    },
    {
        "s_no": 291,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. M.M. Armstrong Arasu",
        "designation": "Assistant Professor",
        "email": "armstrongarasu_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 292,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. A. J. Clement Lourduraj",
        "designation": "Assistant Professor",
        "email": "clementlourduraj_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 293,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. M. Antony Arockiaraj",
        "designation": "Assistant Professor",
        "email": "antonyarockiaraj_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 294,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. R. Jerald Vijay",
        "designation": "Assistant Professor",
        "email": "jeraldvijay_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 295,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. S. Dinakaran",
        "designation": "Assistant Professor",
        "email": "dinakaran_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 296,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. S. Anbarasu",
        "designation": "Assistant Professor",
        "email": "anbarasu_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 297,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. A. Antony Raj",
        "designation": "Assistant Professor",
        "email": "antonyraj_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 298,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. G. Samuel",
        "designation": "Assistant Professor",
        "email": "samuel_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 299,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. H. Joy Prabu",
        "designation": "Assistant Professor",
        "email": "joyprabu_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 300,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. R. Thomas",
        "designation": "Assistant Professor",
        "email": "thomasr_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 301,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. S. Prathap",
        "designation": "Assistant Professor",
        "email": "prathaps_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 302,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. A. Alexandar",
        "designation": "Assistant Professor",
        "email": "alexandar_ph1@mail.sjctni.edu",
        "shift": "I",
        "category": "Aided",
        "gender": "M"
    },
    {
        "s_no": 303,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. S. Lourduraj",
        "designation": "Assistant Professor",
        "email": "lourduraj_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 304,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. P. Adal Arasu",
        "designation": "Assistant Professor",
        "email": "adalarasu_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 305,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. A. Sinthiya",
        "designation": "Assistant Professor",
        "email": "sinthiya_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 306,
        "school": "SPS",
        "department": "Physics",
        "name": "Ms. B. Mary Dayana",
        "designation": "Assistant Professor",
        "email": "marydayana_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 307,
        "school": "SPS",
        "department": "Physics",
        "name": "Mr. G. Novin Senetra Roy",
        "designation": "Assistant Professor",
        "email": "novinsenetraroy_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 308,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. M. Augustin",
        "designation": "Assistant Professor",
        "email": "augustin_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 309,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. G. Genifer Silvena",
        "designation": "Assistant Professor",
        "email": "genifersilvena_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "F"
    },
    {
        "s_no": 310,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. S. Rex Rosario",
        "designation": "Assistant Professor",
        "email": "rexrosario_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Coordinator",
        "gender": "M"
    },
    {
        "s_no": 311,
        "school": "SPS",
        "department": "Physics",
        "name": "Dr. T. Kaviya",
        "designation": "Assistant Professor",
        "email": "kaviya_ph2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 312,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Mr. K. Michael Raj",
        "designation": "Assistant Professor",
        "email": "michaelraj_he@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 313,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Dr. A. Saran Raj",
        "designation": "Assistant Professor",
        "email": "saranraj_he@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 314,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Mr. A. Philip Arun Kennedy",
        "designation": "Assistant Professor",
        "email": "philiparunkennedy_he@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 315,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Ms. R. Kavitha",
        "designation": "Assistant Professor",
        "email": "kavitha_he@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "F"
    },
    {
        "s_no": 316,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Mr. J. Rajesh Kumar",
        "designation": "Assistant Professor",
        "email": "rajeshkumar_he2@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    },
    {
        "s_no": 317,
        "school": "OTHERS",
        "department": "Human Excellence",
        "name": "Mr. B. Sushvinth",
        "designation": "Assistant Professor",
        "email": "sushvinth_he@mail.sjctni.edu",
        "shift": "II",
        "category": "Secretary",
        "gender": "M"
    }
];

// Auto-sync custom added and deleted faculty from localStorage
(function initFacultyStorageSync() {
    if (typeof window === 'undefined') return;

    window.syncCustomFacultyFromStorage = function() {
        try {
            const custom = JSON.parse(localStorage.getItem('sjc_custom_faculty_list') || '[]');
            const deleted = JSON.parse(localStorage.getItem('sjc_deleted_faculty_list') || '[]');

            // Remove locally deleted faculty
            if (Array.isArray(deleted) && deleted.length > 0) {
                deleted.forEach(del => {
                    const idx = MASTER_FACULTY_ROSTER.findIndex(f => 
                        (f.name || '').trim().toLowerCase() === (del.name || '').trim().toLowerCase() && 
                        (f.department || '').trim().toLowerCase() === (del.department || '').trim().toLowerCase()
                    );
                    if (idx !== -1) {
                        MASTER_FACULTY_ROSTER.splice(idx, 1);
                    }
                });
            }

            // Append or update custom faculty
            if (Array.isArray(custom)) {
                custom.forEach(cf => {
                    const idx = MASTER_FACULTY_ROSTER.findIndex(f => 
                        (f.name || '').trim().toLowerCase() === (cf.name || '').trim().toLowerCase() && 
                        (f.department || '').trim().toLowerCase() === (cf.department || '').trim().toLowerCase()
                    );
                    if (idx !== -1) {
                        MASTER_FACULTY_ROSTER[idx] = { ...MASTER_FACULTY_ROSTER[idx], ...cf };
                    } else {
                        MASTER_FACULTY_ROSTER.push(cf);
                    }
                });
            }
        } catch (e) {
            console.warn('Storage sync error:', e);
        }
    };

    window.syncCustomFacultyFromStorage();
})();
